### PR TITLE
Add configuration options `terminateTimeoutMs` and `terminateGracePeriodMs`

### PR DESCRIPTION
**Pull request by Leokuma**
I'm submitting this PR for evaluation. Let me know if something is bad or if this is a bad idea altogether.

These new process options only work with the global command `pup terminate` (at least for now). They don't affect the `stop` command or the cron `terminate` option.

- `terminateWaitFinishMs` (optional): Once a termination is triggered by `pup terminate`, this number specifies how long to wait (in milliseconds) for a process to finish _by itself_ before actually asking it to terminate.
- `terminateTimeoutMs` (optional): Once a termination is triggered by `pup terminate`, this number specifies how long to wait (in milliseconds) for a process to terminate before killing it. Defaults to 30s. Before this PR, this timeout was global for all processes and fixed at 30s.

### Rationale
This PR adds more control over how processes are terminated.

It seems that Windows has a problem to terminate processes gracefully. For instance, I wasn't able to make Windows wait for a `sleep 5` to finish before exiting Pup. Now with `terminateWaitFinishMs` it's possible to some degree.

Another problem is that apparently Dax only sends SIGKILL signals, not SIGTERM.

Finally, setting different termination timeouts for each process is useful when some processes are expected to terminate quickly while others might take a long time to finish.

⚠️ **Problem**: I wasn't able to make Pup clear those KV files upon termination. Not sure if they should actually be deleted.

### CODE REVIEW

**Comment by Hexagon** [comment]
Cool, this is looking good! Here are some thoughts:

* What do you think about renaming `terminateWaitFinishMs` to `terminateGracePeriodMs` to further clarify that it is a period for a graceful shutdown?
* These settings should be duplicated in the global scope, so there are defaults, optional global overrides, and optional per-process overrides.
* I have not really thought this through... But it feels like it would make sense to consider these settings on `stop` and (cron) `terminate` too, wouldn't it?

All KV files will be moved to persistent storage in an upcoming update, so they are expected to remain on disk post-shutdown.

**Comment by Leokuma** [comment]
> What do you think about renaming terminateWaitFinishMs to terminateGracePeriodMs to further clarify that it is a period for a graceful shutdown?

Will do 👍. I thought so much about a name for that config and couldn't come up with anything good 😅.

> it would make sense to consider these settings on stop and (cron) terminate too, wouldn't it?

Yes. I didn't do that just because I think it would be a considerably big change and I'd like to get your feedback first on the overall idea and how to execute it. Should we turn [`Process.stop()`](https://github.com/Hexagon/pup/blob/main/lib/core/process.ts#L254) into a promise that would take into account all the timeouts? It will require changing some places where it's called.

I will follow your other remarks too. Thanks for the review!

**Comment by Hexagon** [comment]
> Yes. I didn't do that just because I think it would be a considerably big change and I'd like to get your feedback first on the overall idea and how to execute it. Should we turn [`Process.stop()`](https://github.com/Hexagon/pup/blob/main/lib/core/process.ts#L254) into a promise that would take into account all the timeouts? It will require changing some places where it's called.

Thumbs up on this, try it out and see where it leads us 😄

**Comment by Hexagon** [comment]
@Leokuma 

Had to make some changes to get graceful shutdown working at all, sorry if i'm interfering with your work 🙈 

https://github.com/Hexagon/pup/commit/b15413d1a56798be1e9946c4e5d97745ad4b6599

**Comment by Leokuma** [comment]
@Hexagon I'm finally back after very busy weeks. I _think_ I will have a little more free time in the next few days.

I was wondering... Should we have the timeouts configs in seconds or ms? `sleep` command takes seconds, Windows' `timeout` command takes seconds, IIS webserver takes seconds. Maybe we should use seconds too? People would still be able to specify subseconds with like `0.5` or `1.3`.

**Comment by Hexagon** [comment]
Great! Yeah seconds sound more reasonable than ms :+1:

**Pull request closed without merging**
